# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url:  https://github.com/shawnmcgough/flask-sample-app/discussions
    about: Please use discussions for questions